### ISSUE TITLE
Особености главной кнопки

### ISSUE THREAD

**Issue by ysset** [DobbiKov/telegram-bot-web-app#1]
Привет, у меня mainButton евенты вызываются 2 и болеее раз если находятся их внутри react компонента, ты встречался с подобной проблемой?

**Comment by DobbiKov** [comment]
Sorry. Haven't understood your question. Can you say a bit more about it?

**Comment by ysset** [comment]
> Sorry. Haven't understood your question. Can you say a bit more about it?
> 
> 

Oh,k, I just have a problem, mainButton event call twice if inside the react component
